### ISSUE TITLE
Using RKE2 with registry mirror

### ISSUE THREAD

**Issue by bashofmann** [rancher/barn#8]
Should include instructions how to install and configure a registry mirror for docker hub

**Comment by frank-at-suse** [comment]
RKE2 mirroring docs are [HERE](https://docs.rke2.io/install/containerd_registry_configuration?_highlight=mirror#mirrors).  This issue was opened _before_ that page was published, so I'm going to close.  If we need to go deeper with mirroring at some point in the future, we can re-open.
